Repository finos/FDC3, pull requests merged in 2019-03, with the labels that each got.

#25 Renamed help.js -> get-involved.js and built the page out
  website/pages/en/get-involved.js
  website/pages/en/help.js
  website/siteConfig.js
Labels: cla-present, docs

#27 Compliance
  docs/fdc3-charter.md
  docs/fdc3-compliance.md
  website/sidebars.json
Labels: cla-present

#28 Intents content
  docs/intents-intro.md
  docs/intents-spec.md
Labels: cla-present

#29 Context content
  docs/context-intro.md
  docs/context-spec.md
Labels: cla-present

#31 removed people list
  docs/use-cases/intro.md
Labels: cla-present

#24 Migrate use cases from use case repo
  docs/assets/uc4.png
  docs/assets/uc5.png
  docs/use-cases/2018-06-08-001-equity-sell-side-trader.md
  docs/use-cases/2018-09-20-009-call-transcription-to-crm.md
  docs/use-cases/2018-09-20-010-realtime-trade-ticket-population.md
  docs/use-cases/2018-10-02-004-client-side-fx-trader.md
  docs/use-cases/2018-10-02-005-buy-side-treasurer.md
  docs/use-cases/2018-11-07-006-dynamic-discovery-in-chat.md
  docs/use-cases/2018-11-07-007-platform-agnostic-interop-api.md
  docs/use-cases/2019-01-10-002-buy-side-portfolio-manager.md
  docs/use-cases/2019-02-26-003-inhouse-cross-platform-launcher.md
  docs/use-cases/2019-02-26-013-user-launches-multiple-apps-from-a-single-container.md
  docs/use-cases/overview.md
  website/sidebars.json
  website/siteConfig.js
Labels: cla-present, use-cases

#41 Remove unneccesary dates from filenames
  docs/use-cases/001-equity-sell-side-trader.md
  docs/use-cases/002-buy-side-portfolio-manager.md
  docs/use-cases/003-inhouse-cross-platform-launcher.md
  docs/use-cases/004-client-side-fx-trader.md
  docs/use-cases/005-buy-side-treasurer.md
  docs/use-cases/009-call-transcription-to-crm.md
  docs/use-cases/010-realtime-trade-ticket-population.md
  docs/use-cases/013-user-launches-multiple-apps-from-a-single-container.md
Labels: cla-present

#34 docs: light touch edit
  docs/api/DesktopAgent.md
  docs/api/api-intro.md
  docs/appd-discovery.md
  docs/appd-intro.md
  docs/appd-use.md
  docs/context-intro.md
  docs/context-spec.md
  docs/fdc3-charter.md
  docs/fdc3-compliance.md
  docs/fdc3-intro.md
  docs/why-fdc3.md
Labels: cla-present

#47 Create 1.0-beta version of FDC3 docs
  website/pages/en/versions.js
  website/versioned_docs/version-1.0-beta/api/Context.md
  website/versioned_docs/version-1.0-beta/api/DesktopAgent.md
  website/versioned_docs/version-1.0-beta/api/Errors.md
  website/versioned_docs/version-1.0-beta/api/api-intro.md
  website/versioned_docs/version-1.0-beta/api/api-spec.md
  website/versioned_docs/version-1.0-beta/appd-discovery.md
  website/versioned_docs/version-1.0-beta/appd-intro.md
  website/versioned_docs/version-1.0-beta/appd-spec.md
  website/versioned_docs/version-1.0-beta/appd-use.md
  website/versioned_docs/version-1.0-beta/context-intro.md
  website/versioned_docs/version-1.0-beta/context-spec.md
  website/versioned_docs/version-1.0-beta/fdc3-charter.md
  website/versioned_docs/version-1.0-beta/fdc3-compliance.md
  website/versioned_docs/version-1.0-beta/fdc3-intro.md
  website/versioned_docs/version-1.0-beta/intents-intro.md
  website/versioned_docs/version-1.0-beta/intents-spec.md
  website/versioned_docs/version-1.0-beta/use-cases/001-equity-sell-side-trader.md
  website/versioned_docs/version-1.0-beta/use-cases/002-buy-side-portfolio-manager.md
  website/versioned_docs/version-1.0-beta/use-cases/003-inhouse-cross-platform-launcher.md
  website/versioned_docs/version-1.0-beta/use-cases/004-client-side-fx-trader.md
  website/versioned_docs/version-1.0-beta/use-cases/005-buy-side-treasurer.md
  website/versioned_docs/version-1.0-beta/use-cases/009-call-transcription-to-crm.md
  website/versioned_docs/version-1.0-beta/use-cases/010-realtime-trade-ticket-population.md
  website/versioned_docs/version-1.0-beta/use-cases/013-user-launches-multiple-apps-from-a-single-container.md
  website/versioned_docs/version-1.0-beta/use-cases/overview.md
  website/versioned_docs/version-1.0-beta/why-fdc3.md
  website/versioned_sidebars/version-1.0-beta-sidebars.json
  website/versions.json
Labels: cla-present, website

#49 Added UC-15
  docs/use-cases/015-sales-floor-base-workflow.md
  website/sidebars.json
Labels: cla-present

#50 added references links
  docs/fdc3-compliance.md
Labels: cla-present

#51 Capture version 1.0 of docs
  website/pages/en/versions.js
  website/siteConfig.js
  website/versioned_docs/version-1.0/api/Context.md
  website/versioned_docs/version-1.0/api/DesktopAgent.md
  website/versioned_docs/version-1.0/api/Errors.md
  website/versioned_docs/version-1.0/api/api-intro.md
  website/versioned_docs/version-1.0/api/api-spec.md
  website/versioned_docs/version-1.0/appd-discovery.md
  website/versioned_docs/version-1.0/appd-intro.md
  website/versioned_docs/version-1.0/appd-spec.md
  website/versioned_docs/version-1.0/appd-use.md
  website/versioned_docs/version-1.0/context-intro.md
  website/versioned_docs/version-1.0/context-spec.md
  website/versioned_docs/version-1.0/fdc3-charter.md
  website/versioned_docs/version-1.0/fdc3-compliance.md
  website/versioned_docs/version-1.0/fdc3-intro.md
  website/versioned_docs/version-1.0/intents-intro.md
  website/versioned_docs/version-1.0/intents-spec.md
  website/versioned_docs/version-1.0/use-cases/001-equity-sell-side-trader.md
  website/versioned_docs/version-1.0/use-cases/002-buy-side-portfolio-manager.md
  website/versioned_docs/version-1.0/use-cases/003-inhouse-cross-platform-launcher.md
  website/versioned_docs/version-1.0/use-cases/004-client-side-fx-trader.md
  website/versioned_docs/version-1.0/use-cases/005-buy-side-treasurer.md
  website/versioned_docs/version-1.0/use-cases/009-call-transcription-to-crm.md
  website/versioned_docs/version-1.0/use-cases/010-realtime-trade-ticket-population.md
  website/versioned_docs/version-1.0/use-cases/013-user-launches-multiple-apps-from-a-single-container.md
  website/versioned_docs/version-1.0/use-cases/015-sales-floor-base-workflow.md
  website/versioned_docs/version-1.0/use-cases/overview.md
  website/versioned_docs/version-1.0/why-fdc3.md
  website/versioned_sidebars/version-1.0-beta-sidebars.json
  website/versioned_sidebars/version-1.0-sidebars.json
  website/versions.json
Labels: cla-present

#54 Update index.js - use cases one liner
  website/pages/en/index.js
Labels: cla-present

#55 added roadmap
  README.md
Labels: cla-present

#57 Add new FDC3 icons and fix index page URLs
  website/core/Footer.js
  website/pages/en/index.js
  website/static/css/custom.css
  website/static/img/feature-api.svg
  website/static/img/feature-appd.svg
  website/static/img/feature-context.svg
  website/static/img/feature-intents.svg
Labels: cla-present

#56 Fix #35 by applying FINOS darker blue colour to header
  website/siteConfig.js
Labels: cla-present

#65 Fix intent examples in docs
  docs/intents-intro.md
  website/versioned_docs/version-1.0/intents-intro.md
Labels: cla-present

#66 Change `findIntentsForContext` -> `findIntentsByContext` in example
  docs/api/DesktopAgent.md
  website/versioned_docs/version-1.0/api/DesktopAgent.md
Labels: cla-present

#68 Set FINOS badge to “Released” ahead of 1.0 release
  README.md
Labels: cla-present, repo

#67 Add user showcase to website
  website/core/Showcase.js
  website/data/users.json
  website/pages/en/index.js
  website/pages/en/users.js
  website/siteConfig.js
  website/static/css/custom.css
  website/static/img/finos_wordmark.svg
  website/static/img/users/ChartIQ.webp
  website/static/img/users/Cloud9.webp
  website/static/img/users/FactSet.webp
  website/static/img/users/GLUE42.webp
  website/static/img/users/GreenKey.webp
  website/static/img/users/IHSMarkit.webp
  website/static/img/users/JPMorgan.webp
  website/static/img/users/MorganStanley.webp
  website/static/img/users/Openfin.webp
  website/static/img/users/Refinitiv.webp
  website/static/img/users/adaptive.webp
  website/static/img/users/deutsche-bank.webp
  website/static/img/users/scottlogic.png
Labels: cla-present, website

#69 add hyperlink
  docs/fdc3-intro.md
  website/versioned_docs/version-1.0/fdc3-intro.md
Labels: cla-present

#72 Add CHANGELOG.md with standard format
  CHANGELOG.md
  website/pages/en/versions.js
Labels: cla-present, repo

#73 updated text
  website/pages/en/index.js
Labels: cla-present, website

#77 Appd links to obsolete version of website
  src/app-directory/README.md
Labels: cla-present

#79 Fix broken links and other minor website issues
  docs/api/api-spec.md
  docs/why-fdc3.md
  website/core/Footer.js
  website/package.json
  website/pages/en/index.js
  website/static/css/custom.css
  website/versioned_docs/version-1.0/api/api-spec.md
  website/versioned_docs/version-1.0/why-fdc3.md
  website/yarn.lock
Labels: cla-present, docs, website
