Repository finos/FDC3, pull requests merged in 2019-04, with the labels that each got.

#81 Updated copyright header in POM.xml files for AppD
  src/app-directory/appd-java-server-stubs/pom.xml
  src/app-directory/appd-jersey-client/pom.xml
  src/app-directory/appd-nodejs-server-stubs/pom.xml
  src/app-directory/appd-typescript-angular-client/pom.xml
  src/app-directory/pom.xml
Labels: cla-present

#85 Fix GreenKey URL
  index.html
Labels: cla-present, website

#76 Minor updates to readme to reference CLAs and Wiki
  README.md
Labels: cla-present, repo

#83 Fix typo
  src/app-directory/README.md
Labels: cla-present, repo

#84 Fix typo
  src/app-directory/README.md
Labels: repo

#87 Fix URL for GreenKey in user showcase on website
  website/data/users.json
Labels: cla-present, website
