Repository finos/FDC3, pull requests merged in 2019-07, with the labels that each got.

#100 Added Chart IQ to users.json - display on Home
  website/data/users.json
Labels: cla-present, website

#99 Proposed updated README to reference docs more explicitly
  README.md
Labels: cla-present, repo

#101 added .png versions of Users - changed users.json files to .png
  website/README.md
  website/core/Footer.js
  website/core/img/finos_wordmark.svg
  website/data/users.json
  website/siteConfig.js
  website/static/img/users/FactSet.png
  website/static/img/users/GLUE42.png
  website/static/img/users/GreenKey.png
  website/static/img/users/IHSMarkit.png
  website/static/img/users/JPMorgan.png
  website/static/img/users/Openfin.png
  website/static/img/users/Refinitiv.png
  website/static/img/users/adaptive.png
Labels: cla-present

#104 changed out ChartIQ / Glue42 / GreenKey broken logos - changed footer logo URL
  website/core/Footer.js
  website/static/img/users/ChartIQ.png
  website/static/img/users/GLUE42.png
  website/static/img/users/GreenKey.png
  website/static/img/users/chartiq.png
Labels: cla-present

#103 aligning README.md and CONTRIBUTING.md to FINOS project blueprint language
  README.md
Labels: cla-present

#110 Keep generated OpenAPI appd spec 1.0 in versioned folder
  src/app-directory/specification/appd.yaml
  website/core/Footer.js
  website/pages/1.0/appd-spec.html
  website/pages/appd-spec.html
  website/versioned_docs/version-1.0/appd-spec.md
Labels: app-directory, cla-present, website

#105 Fix #102 by adding code headers
  NOTICE
  examples/context/Contact.ts
  examples/context/ContactList.ts
  examples/context/Country.ts
  examples/context/Instrument.ts
  examples/context/InstrumentList.ts
  examples/context/Organization.ts
  examples/context/Portfolio.ts
  examples/context/Position.ts
  src/api/interface.ts
  src/app-directory/.gitignore
  src/app-directory/appd-java-server-stubs/pom.xml
  src/app-directory/appd-jersey-client/pom.xml
  src/app-directory/appd-nodejs-server-stubs/pom.xml
  src/app-directory/appd-typescript-angular-client/pom.xml
  src/app-directory/pom.xml
  src/context/Context.ts
  src/intents/intent.ts
Labels: cla-present, repo

#107 Upgrade docusaurus and redoc-cli to fix security issues
  src/app-directory/pom.xml
  website/package.json
  website/yarn.lock
Labels: bug, cla-present
