Repository finos/FDC3, pull requests merged in 2020-03, with the labels that each got.

#182 clarified behavior for getCurrentContext
  docs/api/ref/Channel.md
Labels: 1.1, api, cla-present

#181 changed Channel to interface, updated and expanded documentation
  docs/api/ref/Channel.md
  docs/api/spec.md
  src/api/Channel.ts
  website/sidebars.json
Labels: 1.1, api, cla-present

#180 Adding link to footer for FINOS privacy policy
  website/core/Footer.js
Labels: cla-present, website

#179 Update finsemble doc ref
  docs/api/spec.md
  docs/fdc3-charter.md
  docs/intents/overview.md
Labels: cla-present, docs

#183 chore: update CHANGELOG with unreleased changes since 1.0.0
  CHANGELOG.md
Labels: cla-present, repo

#185 alphabetized methods in api reference
  docs/api/ref/Channel.md
  docs/api/ref/DesktopAgent.md
Labels: cla-present

#184 Updating references to approved use cases
  website/sidebars.json
Labels: cla-present

#187 Reference docs for instrument, contact and list types
  docs/context/ref/Contact.md
  docs/context/ref/ContactList.md
  docs/context/ref/Instrument.md
  docs/context/ref/InstrumentList.md
Labels: cla-present

#188 initial additions to ref data for intents
  docs/intents/ref/StartCall.md
  docs/intents/ref/StartChat.md
  docs/intents/ref/ViewAnalysis.md
  docs/intents/ref/ViewChart.md
  docs/intents/ref/ViewContact.md
  docs/intents/ref/ViewInstrument.md
  docs/intents/ref/ViewNews.md
  docs/intents/ref/ViewQuote.md
Labels: cla-present

#189 Reference update for Organization and Country
  docs/context/ref/Country.md
  docs/context/ref/Organization.md
Labels: cla-present

#190 doc updates
  docs/app-directory/discovery.md
  docs/app-directory/overview.md
  docs/app-directory/spec.md
  docs/app-directory/usage.md
  docs/apps-and-platforms.md
  docs/context/ref/Contact.md
  docs/context/ref/ContactList.md
  docs/context/ref/Context.md
  docs/context/ref/Country.md
  docs/context/ref/Instrument.md
  docs/context/ref/InstrumentList.md
  docs/context/ref/Organization.md
  docs/context/ref/Portfolio.md
  docs/context/ref/Position.md
  docs/fdc3-compliance.md
  docs/intents/ref/ViewAnalysis.md
  docs/intents/ref/ViewNews.md
  website/sidebars.json
Labels: 1.1, cla-present, docs, website
