Repository finos/FDC3, pull requests merged in 2021-01, with the labels that each got.

#292 Update meeting minute issue templates
  .github/ISSUE_TEMPLATE/general-meeting.md
  .github/ISSUE_TEMPLATE/pmc-meeting.md
  .github/ISSUE_TEMPLATE/standard-wg-meeting.md
Labels: cla-present

#282 Support nullable return type for getCurrentChannel
  src/api/DesktopAgent.ts
  src/api/methods.ts
Labels: cla-present

#283 Implement missing 'leaveCurrentChannel' method
  src/api/DesktopAgent.ts
  src/api/methods.ts
  test/methods.test.ts
Labels: cla-present

#285 Clarify docs for broadcast functions
  .prettierignore
  docs/api/ref/Channel.md
  docs/api/ref/DesktopAgent.md
  src/api/Channel.ts
  src/api/DesktopAgent.ts
Labels: cla-present

#268 Context Equivalent of RaiseIntent - Issue 213
  docs/api/ref/Context.md
  docs/api/ref/DesktopAgent.md
  docs/api/ref/IntentResolution.md
  docs/api/spec.md
  src/api/DesktopAgent.ts
Labels: cla-present

#302 fix(api): redundant AppMetadata import
  .prettierignore
  package.json
  src/api/DesktopAgent.ts
  yarn.lock
Labels: cla-present

#300 Updating README.md
  README.md
Labels: cla-present

#277 Reject/throw as appropriate in ES6 exported methods if window.fdc3 is not available
  src/api/methods.ts
  test/methods.test.ts
Labels: cla-present

#275 Streamline main readme, and update website versioning
  README.md
  website/core/Footer.js
  website/data/defaultVersion.json
  website/data/users.json
  website/package.json
  website/pages/en/get-involved.js
  website/pages/en/index.js
  website/pages/en/users.js
  website/pages/en/versions.js
  website/siteConfig.js
  website/utils/swapVersions.js
  website/versions.json
Labels: cla-present

#309 chore: update change log to reflect changes since 1.1
  CHANGELOG.md
Labels: cla-present, repo

#307 Desktop agent and Channel implementations should prevent context message loops
  docs/api/spec.md
Labels: api, cla-present

#310 Clarify relationship between Intents and Context in spec
  docs/api/spec.md
Labels: cla-present
